// This file was auto-generated by @insertish/oapi!
import { paths } from './schema';
export type APIRoutes =
| { method: 'get', path: `/regions`, params: undefined, response: paths['/regions']['get']['responses']['200']['content']['application/json'] }
| { method: 'get', path: `/streams/`, params: undefined, response: paths['/streams/']['get']['responses']['200']['content']['application/json'] }
| { method: 'put', path: `/streams/`, params: paths['/streams/']['put']['requestBody']['content']['application/json'], response: paths['/streams/']['put']['responses']['200']['content']['application/json'] }
| { method: 'get', path: `/streams/@me`, params: undefined, response: paths['/streams/@me']['get']['responses']['200']['content']['application/json'] }
| { method: 'patch', path: `/streams/@me`, params: paths['/streams/@me']['patch']['requestBody']['content']['application/json'], response: paths['/streams/@me']['patch']['responses']['200']['content']['application/json'] }
| { method: 'get', path: `/streams/${string}`, params: undefined, response: paths['/streams/{path}']['get']['responses']['200']['content']['application/json'] }
| { method: 'post', path: `/streams/reset_token`, params: undefined, response: paths['/streams/reset_token']['post']['responses']['200']['content']['application/json'] }
| { method: 'get', path: `/users/@me`, params: undefined, response: paths['/users/@me']['get']['responses']['200']['content']['application/json'] }
| { method: 'put', path: `/users/@me`, params: paths['/users/@me']['put']['requestBody']['content']['application/json'], response: paths['/users/@me']['put']['responses']['200']['content']['application/json'] }
| { method: 'patch', path: `/users/@me`, params: paths['/users/@me']['patch']['requestBody']['content']['application/json'], response: paths['/users/@me']['patch']['responses']['200']['content']['application/json'] }
| { method: 'get', path: `/users/${string}`, params: undefined, response: paths['/users/{path}']['get']['responses']['200']['content']['application/json'] }
| { method: 'post', path: `/categories/create`, params: paths['/categories/create']['post']['requestBody']['content']['application/json'], response: paths['/categories/create']['post']['responses']['200']['content']['application/json'] }
| { method: 'delete', path: `/categories/${string}`, params: undefined, response: undefined }
| { method: 'patch', path: `/categories/${string}`, params: paths['/categories/{id}']['patch']['requestBody']['content']['application/json'], response: paths['/categories/{id}']['patch']['responses']['200']['content']['application/json'] }
| { method: 'get', path: `/categories/`, params: undefined, response: paths['/categories/']['get']['responses']['200']['content']['application/json'] }
| { method: 'get', path: `/chat/${string}/messages`, params: undefined, response: paths['/chat/{target}/messages']['get']['responses']['200']['content']['application/json'] }
| { method: 'post', path: `/chat/${string}/messages`, params: paths['/chat/{target}/messages']['post']['requestBody']['content']['application/json'], response: paths['/chat/{target}/messages']['post']['responses']['200']['content']['application/json'] }
| { method: 'delete', path: `/chat/${string}/messages/${string}`, params: undefined, response: undefined }
| { method: 'post', path: `/auth/account/create`, params: paths['/auth/account/create']['post']['requestBody']['content']['application/json'], response: undefined }
| { method: 'post', path: `/auth/account/reverify`, params: paths['/auth/account/reverify']['post']['requestBody']['content']['application/json'], response: undefined }
| { method: 'get', path: `/auth/account/`, params: undefined, response: paths['/auth/account/']['get']['responses']['200']['content']['application/json'] }
| { method: 'patch', path: `/auth/account/change/password`, params: paths['/auth/account/change/password']['patch']['requestBody']['content']['application/json'], response: undefined }
| { method: 'patch', path: `/auth/account/change/email`, params: paths['/auth/account/change/email']['patch']['requestBody']['content']['application/json'], response: undefined }
| { method: 'post', path: `/auth/account/verify/${string}`, params: undefined, response: undefined }
| { method: 'post', path: `/auth/account/reset_password`, params: paths['/auth/account/reset_password']['post']['requestBody']['content']['application/json'], response: undefined }
| { method: 'patch', path: `/auth/account/reset_password`, params: paths['/auth/account/reset_password']['patch']['requestBody']['content']['application/json'], response: undefined }
| { method: 'post', path: `/auth/session/login`, params: paths['/auth/session/login']['post']['requestBody']['content']['application/json'], response: paths['/auth/session/login']['post']['responses']['200']['content']['application/json'] }
| { method: 'post', path: `/auth/session/logout`, params: undefined, response: undefined }
| { method: 'get', path: `/auth/session/all`, params: undefined, response: paths['/auth/session/all']['get']['responses']['200']['content']['application/json'] }
| { method: 'delete', path: `/auth/session/all`, params: paths['/auth/session/all']['delete']['parameters']['query'], response: undefined }
| { method: 'delete', path: `/auth/session/${string}`, params: undefined, response: undefined }
| { method: 'patch', path: `/auth/session/${string}`, params: paths['/auth/session/{id}']['patch']['requestBody']['content']['application/json'], response: paths['/auth/session/{id}']['patch']['responses']['200']['content']['application/json'] };